

CREATE TABLE Source_Website (
  URL_ VARCHAR(50) PRIMARY KEY,
  NAME_ VARCHAR(30)
);





CREATE TABLE Record_Vaccine (
  LOCATION_ VARCHAR(50) NOT NULL,
  DATE_ DATETIME NOT NULL,
  VACCINE VARCHAR(50) NOT NULL,
  TOTAL_VACCINES INT NOT NULL,
  PRIMARY KEY (LOCATION_, DATE_, VACCINE)
);





CREATE TABLE Record_age (
  LOCATION_ VARCHAR(50) NOT NULL,
  DATE_ DATETIME NOT NULL,
  AGE_GROUP VARCHAR(50) NOT NULL,
  PEOPLE_VACCINATED_HUND INT,
  PEOPLE_FULLY_VACCINATED_HUND INT,
  TOTAL_BOOSTERS_HUND INT,
  PRIMARY KEY (LOCATION_, DATE_, AGE_GROUP)
);





CREATE TABLE Location_Data_Total (
    LOCATION_ VARCHAR(50) NOT NULL,
    DATE_ DATETIME NOT NULL,
    VACCINES VARCHAR(200),
    SOURCE_WEBSITE VARCHAR(50) NOT NULL,
    TOTAL_VACCINATIONS INT,
    SHARE_DOSES_USED FLOAT,
    TOTAL_DISTRIBUTED INT,
    PRIMARY KEY (LOCATION_, DATE_),
    FOREIGN KEY (SOURCE_WEBSITE) REFERENCES Source_Website(URL_)
);





CREATE TABLE Location_Data_NON_Total (
    LOCATION_ VARCHAR(50) NOT NULL,
    DATE_ DATETIME NOT NULL,
    SOURCE_WEBSITE VARCHAR(50) NOT NULL,
    PEOPLE_VACCINATED INT,
    PEOPLE_FULLY_VACCINATED INT,
    TOTAL_BOOSTERS INT,
    DAILY_PEOPLE_VACCINATED INT,
    DAILY_VACCINATIONS INT,
    PRIMARY KEY (LOCATION_, DATE_),
    FOREIGN KEY (SOURCE_WEBSITE) REFERENCES Source_Website(URL_)
);


CREATE TABLE US_Location (
    LOCATION_ VARCHAR(50) NOT NULL,
    PRIMARY KEY (LOCATION_)
);

CREATE TABLE Iso_Location (
    LOCATION_ VARCHAR(50) NOT NULL,
    ISO_CODE VARCHAR(50) NOT NULL,
    PRIMARY KEY (LOCATION_)
);

CREATE TABLE Location_Data_Per (
    LOCATION_ VARCHAR(50) NOT NULL,
    DATE_ DATETIME NOT NULL,
    DAILY_VACCINATIONS_RAW INT,
    TOTAL_VACCINATIONS_PER_HUNDRED FLOAT,
    PEOPLE_VACCINATED_PER_HUNDRED FLOAT,
    PEOPLE_FULLY_VACCINAT_PER_HUNDRED FLOAT,
    TOTAL_BOOSTERS_PER_HUNDRED FLOAT,
    DAILY_VACCINATIONS_PER_MILLION INT,
    DAILY_PEOPLE_VACCINATED_PER_HUNDRED FLOAT,
    DISTRIBUTED_PER_HUNDRED FLOAT,
    PRIMARY KEY (LOCATION_, DATE_)
);
